#!/usr/bin/python

# Matthew Wyczalkowski
# m.wyczalkowski@wustl.edu
# Washington University School of Medicine

import sys, os;

def main():
    from optparse import OptionParser
    usage_text = """usage: %prog [options] ...
        Process list of generated by stat of file optoins
        """

    parser = OptionParser(usage_text, version="$Revision: 1.2 $")
    parser.add_option("-i", dest="infn", default="stdin", help="Input filename")
    parser.add_option("-o", dest="outfn", default="stdout", help="Output filename")

    (options, params) = parser.parse_args()

#    if (len(params) != 3):
#        parser.error("Pass 3 arguments.")

    if options.infn == "stdin":
        f = sys.stdin
    else:
        f = open(options.infn, 'r')
    if options.outfn == "stdout":
        o = sys.stdout
    else:
        o = open(options.outfn, "w")

    for line in f:
#     1  file_name aka path
#     2  file_type
#     3  total_size
#     4  owner_name
#     5  time_mod
#     6  hard_links

        (path, file_type, total_size, owner_name, time_mod, hard_links) = line.rstrip().split("\t")
        # Skip headers
        if path.startswith("#"): continue

        # Process only regular files
        if file_type == "regular file": 
            # From a complete path, extract 1) dirname, 2) filename, 3) extension.  Note that filename includes extension
            dirname = os.path.dirname(path)
            filename = os.path.basename(path)
            dirname = os.path.dirname(path)
            base, ext = os.path.splitext(filename)
        else:
            dirname = path
            filename = ""
            ext = ""

        o.write('\t'.join( (dirname, filename, ext, file_type, total_size, owner_name, time_mod, hard_links))+"\n")

    f.close()
    o.close()

if __name__ == '__main__':
    main()

