# Matthew Wyczalkowski
# m.wyczalkowski@wustl.edu
# Ding Lab, Washington University School of Medicine

# Usage: Rscript summarize_fs.sh [options] in.dat out.dat
#
# Process file summary output as generated by parse_fs.py and generate summary data
# by grouping data files by owner and extension.  Expected columns of input:
#   dirname, filename, ext, file_type, file_size, owner_name, time_mod, hard_links

# Args:
# -v: verbose output
# -Z: input is a .gz file

library("plyr")

# Return the command line argument associated with a given flag (i.e., -o foo),
# or the default value if argument not specified.
# Note that this will break if an argument is not supplied after the flag.
get_val_arg = function(args, flag, default) {
    ix = pmatch(flag, args)
    if (!is.na(ix)){ val = args[ix+1] } else { val = default }
    return(val)
}

# Return boolean specifying whether given flag appears in command line (i.e., -o),
get_bool_arg = function(args, flag) {
    ix = pmatch(flag, args)
    if (!is.na(ix)){ val = TRUE } else { val = FALSE }
    return(val)
}

# Usage:
#   args = parse_args()
#   print(args$disease.filter)
parse_args = function() {
    args = commandArgs(trailingOnly = TRUE)

    # optional arguments
    verbose = get_bool_arg(args, "-v")
    topN = as.numeric(get_val_arg(args, "-N", 250))
    is.gz = get_bool_arg(args, "-Z")

    # mandatory positional arguments.  These are popped off the back of the array, last one listed first.
    out.fn = args[length(args)];   args = args[-length(args)]
    in.fn = args[length(args)];    args = args[-length(args)]

    val = list( 'in.fn'=in.fn, 'verbose'=verbose, 'out.fn'=out.fn, 'topN'=topN, 'is.gz'=is.gz)
    if (val$verbose) { print(val) }
    return (val)
}

args = parse_args()

# Read in tsv file and keep only regular file entries
# we are interested only in the following columns:
#   file_size, ext, owner_name
# for large datasets we don't want to store unnecessary data
# look at colClasses: https://stat.ethz.ch/R-manual/R-devel/library/utils/html/read.table.html
#
#  1 SKIP  # dirname
#  2 SKIP  filename
#  3 KEEP  ext
#  4 SKIP  file_type
#  5 KEEP  file_size
#  6 KEEP  owner_name
#  7 SKIP  time_mod
#  8 SKIP  hard_links

colClasses=c("NULL", "NULL", "character", "NULL", "numeric", "character", "NULL", "NULL")

if (args$is.gz) {
    FSA = read.csv(gzfile(args$in.fn), sep="\t", colClasses=colClasses);
} else {
    FSA = read.csv(args$in.fn, sep="\t", colClasses=colClasses);
}

rFSA=ddply(FSA, c("ext","owner_name"), summarise,count=length(file_size),cumulative_size=sum(file_size))

write.table(rFSA, args$out.fn, sep="\t", quote=FALSE, row.names=FALSE)
cat(sprintf("    Saved to %s\n", args$out.fn))


