---
title: "FSAudit"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load the ggplot2 library
```{r}
library(ggplot2)
```
```{r}
#data.fn<-"/Users/mwyczalk/Projects/FSAudit/FSAudit/dat/gc2737.processed.100K.dat"
data.fn<-"/Users/mwyczalk/Projects/FSAudit/FSAudit/dat/gc2737.processed.dat"
FSA<-read.csv(data.fn, sep="\t")
```
```{r}
FSA<-FSA[FSA$file_type=="regular file",]
print(FSA)
```
```{r}
library(plyr)
#rFSA=ddply(FSA, c("ext","owner_name"), summarise, N=length(filename), tot_size=length(total_size))
rFSA=ddply(FSA, c("ext","owner_name"), summarise,N=length(total_size),tot_size=sum(total_size))
# get top 100 entries by size
```
```{r}
rFSA100=head(arrange(rFSA,desc(tot_size)),n=250)
rFSA100$tot_size_Tb = rFSA100$tot_size / 1000000000000
print(head(rFSA100))
```

```{r}
p <- ggplot(data=rFSA100)
p <- p + geom_point(aes(x=ext, y=owner_name, size=tot_size_Tb)) + scale_size_area()
p <- p + theme(axis.text.x  = element_text(angle=90, vjust=0.5, hjust=1))
p
```